--- 
abstract: declarative testing for your web app
author: 
  - Best Practical Solutions, LLC
build_requires: 
  HTTP::Server::Simple: 0.35
  Test::Tester: 0.107
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-WWW-Declare
no_index: 
  directory: 
    - inc
    - t
requires: 
  Test::Builder: 0
  Test::More: 0
  Test::WWW::Mechanize: 0
version: 0.02
