--- 
abstract: declarative testing for your web app
author: Shawn M Moore C<< <sartak@bestpractical.com> >>
build_requires: 
  HTTP::Server::Simple::CGI: 0
  Test::Tester: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-WWW-Declare
no_index: 
  directory: 
    - inc
    - t
requires: 
  Test::Builder: 0
  Test::More: 0
  Test::WWW::Mechanize: 0
version: 0.01_01
